
# Q.1 Compare total revenue generated by male vs. female customers.
-- SELECT gender, SUM(purchase_amount) as revenue
-- FROM customer
-- GROUP BY gender

# Q.2 Identify customers who used discounts but still spent above the average purchase amount.
-- SELECT customer_id,purchase_amount
-- FROM customer
-- WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

# Q.3 Find top 5 products with the highest average review ratings
-- SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
-- FROM customer
-- GROUP BY item_purchased
-- ORDER BY AVG(review_rating) desc
-- limit 5;

# Q.4 Compare average purchase amounts between Standard and Express shipping.
-- SELECT shipping_type,
-- ROUND(AVG(purchase_amount),2) AS "average_purchase"
-- FROM customer
-- WHERE shipping_type IN ('Standard','Express')
-- GROUP BY shipping_type

# Q.5 Compare average spend and total revenue across subscription status.
# Subscribers vs. Non-Subscribers
-- SELECT subscription_status,
-- COUNT(customer_id) AS total_customers,
-- ROUND(AVG(purchase_amount),2) AS avg_spend,
-- ROUND(SUM(purchase_amount),2) AS total_revenue
-- FROM customer
-- GROUP BY subscription_status
-- ORDER BY total_revenue DESC, avg_spend DESC;

# Checking for duplicates in customer_id
-- SELECT customer_id, COUNT(*) AS count
-- FROM customer
-- GROUP BY customer_id
-- HAVING COUNT(*) > 1;

# Q.6 Identify 5 products with the highest percentage of discounted purchases.
-- SELECT item_purchased,
-- ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) AS discount_rate
-- FROM customer
-- GROUP BY item_purchased
-- ORDER BY discount_rate DESC
-- limit 5;

# Q.7 Classify customers into New, Returning, and Loyal segments based on purchase history
-- WITH customer_type AS(
-- SELECT customer_id,previous_purchases,
-- CASE
--  WHEN previous_purchases=1 THEN 'New'
--  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
--  ELSE 'Loyal'
--  END AS customer_segment
-- FROM customer)
-- SELECT customer_segment, COUNT(*) AS 'No. of Customers'
-- FROM customer_type
-- GROUP BY customer_segment

# Q.8 List the most purchased products within each category.
-- WITH item_counts AS(
-- SELECT category, item_purchased,
-- COUNT(customer_id) AS total_orders,
-- ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC)AS item_rank
-- FROM customer
-- GROUP BY category, item_purchased)

-- SELECT item_rank, category, item_purchased, total_orders
-- FROM item_counts
-- WHERE item_rank <= 3

# Q.9 Check whether customers with >5 purchases are more likely to subscribe.
-- SELECT subscription_status,
-- COUNT(customer_id) AS total_customers,
-- SUM(previous_purchases > 5) AS repeat_buyers,
--     ROUND(
--         SUM(previous_purchases > 5) / COUNT(customer_id) * 100,
--         2
--     ) AS repeat_buyer_rate
-- FROM customer
-- GROUP BY subscription_status

# Q.10 Calculate total revenue contribution of each age group.
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;






